spring:
  thymeleaf:
    cache: true
  h2:
    console:
      enabled: false

weather:
  imd:
    nowcast:
      mock: false
    rainfall:
      mock: false
    district-warning:
      mock: false
    city:
      mock: false
    aws-data:
      mock: false

logging:
  level:
    root: WARN
    com.example.weathermap: INFO
